models:
  tfidf:
    params:
      ngram_range: [1, 4]
      max_features: 4000
      sublinear_tf: True

  xgboost:
    params:
      n_estimators: 100
      max_depth: 6
      learning_rate: 0.1
      objective: binary:logistic
      booster: gbtree
      colsample_bytree: 0.8
      subsample: 0.8
      gamma: 0
      min_child_weight: 1
      lambda: 1
      alpha: 0

  random_forest:
    params:
      n_estimators: 200
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
      random_state: 42
  
  lightgbm:
    params:
      num_leaves: 31
      max_depth: -1
      num_class: 3
      learning_rate: 0.1
      n_estimators: 100
      objective: multiclass
      boosting_type: gbdt
      colsample_bytree: 0.8
      subsample: 0.8
      min_data_in_leaf: 20
      reg_alpha: 0
      reg_lambda: 0

data:
  preprocessing:
    scaler: StandardScaler
    handle_missing: True
    imputation_strategy: mean
  split:
    test_size: 0.2
    random_state: 42

training:
  batch_size: 32
  epochs: 50
  early_stopping: True
  patience: 5
  learning_rate_schedule: step_decay
  initial_lr: 0.01
  decay_factor: 0.5
  decay_steps: 10

evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1
  cross_validation:
    n_splits: 5
    shuffle: True
    random_state: 42
